language: c

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq --no-install-recommends perl autotools-dev libdbi-dev libldap2-dev libpq-dev libmysqlclient-dev libradiusclient-ng-dev libkrb5-dev libnet-snmp-perl procps mawk
    - sudo apt-get install -qq --no-install-recommends autoconf automake

before_script:
    - tools/setup
    - ./configure

script:
    - make

compiler:
    - clang
    - gcc
#notifications:
#  email: false
